name: DB Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Everyday at 3am UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
        - name: Install pg_dump
          run: sudo apt install -y postgresql-client

        - name: Dump Supabase DB
          run: |
            pg_dump postgresql://${{ vars.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/postgres -F c -f ${{ vars.DB_BACKUP_FILENAME }}
        
        - name: Upload to Backblaze B2
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl private --follow-symlinks
          env: 
            # BackblazeB2 bucket name
            AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
            # BackblazeB2 key id
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # BackblazeB2 app key
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # BackblazeB2 region
            AWS_REGION: ${{ vars.AWS_REGION }}
            # BackblazeB2 endpoint
            AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
            SOURCE_DIR: "."